services:
  ubuntu:
    image: ubuntu:22.04
    container_name: ubuntu_cli
    stdin_open: true     # giữ terminal mở
    tty: true            # cho phép dùng bash
    command: bash

    volumes:
      - ./data:/workspace   # thư mục chia sẻ

    restart: unless-stopped
